import { BadRequestException, ForbiddenException, Injectable, OnModuleInit } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { Client, CopyConditions } from 'minio';
import { createHash } from 'crypto';
export const WORKSPACE_BUCKETS=['workspace-sources','workspace-previews','workspace-assets','workspace-exports','workspace-snapshots','workspace-temp'] as const;export type WorkspaceBucket=typeof WORKSPACE_BUCKETS[number];
export interface WorkspaceObjectContext{organizationId:string;workspaceId:string}
@Injectable()
export class WorkspaceStorageService implements OnModuleInit {private readonly client:Client;constructor(config:ConfigService){this.client=new Client({endPoint:config.getOrThrow('minio.endpoint'),port:config.getOrThrow('minio.port'),useSSL:config.getOrThrow('minio.useSsl'),accessKey:config.getOrThrow('minio.accessKey'),secretKey:config.getOrThrow('minio.secretKey')})}async onModuleInit(){for(const bucket of WORKSPACE_BUCKETS)if(!await this.client.bucketExists(bucket))await this.client.makeBucket(bucket)}
  buildWorkspaceObjectPath(ctx:WorkspaceObjectContext,entityType:string,entityId:string,version:number,filename:string){for(const part of[ctx.organizationId,ctx.workspaceId,entityType,entityId,String(version),filename])this.validateSegment(part);return`${ctx.organizationId}/${ctx.workspaceId}/${entityType}/${entityId}/${version}/${filename}`}
  validateWorkspaceObjectPath(ctx:WorkspaceObjectContext,bucket:string,key:string){if(!WORKSPACE_BUCKETS.includes(bucket as WorkspaceBucket))throw new BadRequestException('Unsupported storage bucket');let decoded:string;try{decoded=decodeURIComponent(decodeURIComponent(key))}catch{throw new BadRequestException('Invalid object path encoding')}if(decoded.startsWith('/')||decoded.includes('\\')||decoded.split('/').some(p=>!p||p==='.'||p==='..'))throw new BadRequestException('Invalid object path');if(!decoded.startsWith(`${ctx.organizationId}/${ctx.workspaceId}/`))throw new ForbiddenException('Object is outside workspace scope');return decoded}
  async createSignedUploadUrl(ctx:WorkspaceObjectContext,bucket:WorkspaceBucket,key:string,ttl=900){return this.client.presignedPutObject(bucket,this.validateWorkspaceObjectPath(ctx,bucket,key),ttl)}async createSignedDownloadUrl(ctx:WorkspaceObjectContext,bucket:WorkspaceBucket,key:string,ttl=900){return this.client.presignedGetObject(bucket,this.validateWorkspaceObjectPath(ctx,bucket,key),ttl)}async objectExists(ctx:WorkspaceObjectContext,bucket:WorkspaceBucket,key:string){try{await this.getObjectMetadata(ctx,bucket,key);return true}catch{return false}}async getObjectMetadata(ctx:WorkspaceObjectContext,bucket:WorkspaceBucket,key:string){return this.client.statObject(bucket,this.validateWorkspaceObjectPath(ctx,bucket,key))}async deleteObject(ctx:WorkspaceObjectContext,bucket:WorkspaceBucket,key:string){await this.client.removeObject(bucket,this.validateWorkspaceObjectPath(ctx,bucket,key))}async copyObject(ctx:WorkspaceObjectContext,sourceBucket:WorkspaceBucket,sourceKey:string,targetBucket:WorkspaceBucket,targetKey:string){const source=this.validateWorkspaceObjectPath(ctx,sourceBucket,sourceKey);const target=this.validateWorkspaceObjectPath(ctx,targetBucket,targetKey);return this.client.copyObject(targetBucket,target,`/${sourceBucket}/${source}`,new CopyConditions())}async storeChecksum(ctx:WorkspaceObjectContext,bucket:WorkspaceBucket,key:string,content:Buffer){const checksum=createHash('sha256').update(content).digest('hex');await this.client.putObject(bucket,this.validateWorkspaceObjectPath(ctx,bucket,key),content,content.length,{'x-amz-meta-checksum-sha256':checksum});return checksum}
  private validateSegment(value:string){let decoded=value;try{decoded=decodeURIComponent(decodeURIComponent(value))}catch{throw new BadRequestException('Invalid path segment')}if(!decoded||decoded==='.'||decoded==='..'||decoded.includes('/')||decoded.includes('\\')||decoded.includes('\0'))throw new BadRequestException('Invalid path segment')}
}
