import { ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { DataSource, EntityManager, Repository } from 'typeorm';
import { UsageDimension, UsageReservation, UsageReservationStatus, WorkspaceUsage } from './entities/usage.entity';
export interface ReserveUsageInput { organizationId:string; workspaceId:string; dimension:UsageDimension; amount:number; idempotencyKey:string; limit?:number }
@Injectable()
export class UsageService {
  constructor(@InjectRepository(UsageReservation) private readonly reservations:Repository<UsageReservation>,private readonly dataSource:DataSource){}
  async reserveUsage(input:ReserveUsageInput,manager?:EntityManager){const run=async(m:EntityManager)=>{const existing=await m.findOne(UsageReservation,{where:{idempotencyKey:input.idempotencyKey}});if(existing)return existing;if(input.amount<=0)throw new ConflictException('Usage amount must be positive');const usage=await m.findOne(WorkspaceUsage,{where:{workspaceId:input.workspaceId},lock:{mode:'pessimistic_write'}});const committed=Number(usage?.totals?.[input.dimension]??0);const raw=await m.createQueryBuilder(UsageReservation,'r').select('COALESCE(SUM(r.amount),0)','total').where('r.workspace_id=:workspaceId AND r.dimension=:dimension AND r.status=:status',{workspaceId:input.workspaceId,dimension:input.dimension,status:UsageReservationStatus.RESERVED}).getRawOne();if(input.limit!==undefined&&committed+Number(raw.total)+input.amount>input.limit)throw new ConflictException('Usage limit exceeded');return m.save(m.create(UsageReservation,{...input,status:UsageReservationStatus.RESERVED,actualAmount:null,expiresAt:new Date(Date.now()+30*60_000)}));};return manager?run(manager):this.dataSource.transaction(run)}
  commitUsage(id:string,actualAmount:number,manager?:EntityManager){return this.finish(id,UsageReservationStatus.COMMITTED,actualAmount,manager)} releaseUsage(id:string,manager?:EntityManager){return this.finish(id,UsageReservationStatus.RELEASED,0,manager)}
  async getUsageSummary(workspaceId:string){return (await this.dataSource.getRepository(WorkspaceUsage).findOne({where:{workspaceId}}))?.totals??{}}
  cleanupExpired(){return this.reservations.createQueryBuilder().update().set({status:UsageReservationStatus.EXPIRED}).where('status=:status AND expires_at<now()',{status:UsageReservationStatus.RESERVED}).execute()}
  private async finish(id:string,status:UsageReservationStatus,actual:number,manager?:EntityManager){const run=async(m:EntityManager)=>{const r=await m.findOne(UsageReservation,{where:{id},lock:{mode:'pessimistic_write'}});if(!r)throw new NotFoundException('Usage reservation not found');if(r.status!==UsageReservationStatus.RESERVED)return r;r.status=status;r.actualAmount=actual;await m.save(r);if(status===UsageReservationStatus.COMMITTED){let u=await m.findOne(WorkspaceUsage,{where:{workspaceId:r.workspaceId},lock:{mode:'pessimistic_write'}});if(!u)u=m.create(WorkspaceUsage,{organizationId:r.organizationId,workspaceId:r.workspaceId,totals:{}});u.totals={...u.totals,[r.dimension]:Number(u.totals[r.dimension]??0)+actual};await m.save(u)}return r};return manager?run(manager):this.dataSource.transaction(run)}
}
