import { BadRequestException, Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { PlatformAuditLog } from './entities/platform-audit-log.entity';
export interface CreateAuditLogInput { organizationId:string; workspaceId?:string; actorId:string; action:string; entityType:string; entityId:string; before?:Record<string,unknown>; after?:Record<string,unknown>; correlationId:string; }
@Injectable()
export class PlatformAuditService {
  constructor(@InjectRepository(PlatformAuditLog) private readonly logs: Repository<PlatformAuditLog>) {}
  async createAuditLog(input: CreateAuditLogInput): Promise<void> { if ('id' in input) throw new BadRequestException('Audit IDs are generated by the platform'); await this.logs.insert({ organizationId:input.organizationId, workspaceId:input.workspaceId??null, actorId:input.actorId, action:input.action, entityType:input.entityType, entityId:input.entityId, before:input.before??null, after:input.after??null, correlationId:input.correlationId }); }
  listForWorkspace(organizationId:string,workspaceId:string) { return this.logs.find({ where:{organizationId,workspaceId}, order:{createdAt:'DESC'} }); }
}
