import * as Joi from 'joi';

export const envSchema = Joi.object({
  NODE_ENV: Joi.string().valid('development', 'test', 'production').required(),
  PORT: Joi.number().required(),
  DATABASE_URL: Joi.string().uri().required(),
  NATS_URL: Joi.string().uri().required(),
  NATS_STREAM_NAME: Joi.string().default('FLOWFORGE'),
  NATS_USER: Joi.string().optional(),
  NATS_PASSWORD: Joi.string().optional(),
  REDIS_URL: Joi.string().uri().default('redis://localhost:6379'),
  REDIS_CONNECT_TIMEOUT_MS: Joi.number().default(5000),
  REDIS_KEY_PREFIX: Joi.string().default('platform:'),
  JWT_ACCESS_SECRET: Joi.string().min(32).required(),
  JWT_REFRESH_SECRET: Joi.string().min(32).required(),
  JWT_ACCESS_TTL: Joi.string().default('15m'),
  JWT_REFRESH_TTL: Joi.string().default('7d'),
  INTERNAL_AUTH_SECRET: Joi.string().min(32).required(),
  INTERNAL_AUTH_PREVIOUS_SECRET: Joi.string().min(32).allow('').optional(),
  INTERNAL_AUTH_ISSUER: Joi.string().default('nestjs-platform'),
  INTERNAL_AUTH_AUDIENCE: Joi.string().default('fastapi-workers'),
  INTERNAL_AUTH_ALLOWED_SERVICES: Joi.string().default('ai-orchestrator,document-worker,research-worker,media-worker,export-worker'),
  INTERNAL_AUTH_TOKEN_TTL_SECONDS: Joi.number().min(30).max(3600).default(300),
  MINIO_ENDPOINT: Joi.string().required(),
  MINIO_PORT: Joi.number().default(9000),
  MINIO_USE_SSL: Joi.boolean().default(false),
  MINIO_ACCESS_KEY: Joi.string().required(),
  MINIO_SECRET_KEY: Joi.string().required(),
  MINIO_BUCKET_ENCRYPTION_ENABLED: Joi.boolean().default(true),
  MINIO_BUCKET_NAME: Joi.string().default('documents'),
  MINIO_BUCKET_DOCUMENTS: Joi.string().default('documents'),
  MINIO_BUCKET_EXPORTS: Joi.string().default('exports'),
  MINIO_BUCKET_SOURCES: Joi.string().default('workspace-sources'),
  MINIO_BUCKET_PREVIEWS: Joi.string().default('workspace-previews'),
  MINIO_BUCKET_ASSETS: Joi.string().default('workspace-assets'),
  MINIO_BUCKET_WORKSPACE_EXPORTS: Joi.string().default('workspace-exports'),
  MINIO_BUCKET_SNAPSHOTS: Joi.string().default('workspace-snapshots'),
  MINIO_BUCKET_TEMP: Joi.string().default('workspace-temp'),
  FASTAPI_ENABLED: Joi.boolean().default(false),
  OLLAMA_ENABLED: Joi.boolean().default(false),
  ELSA_ENABLED: Joi.boolean().default(false),
  OLLAMA_URL: Joi.string().uri().optional(),
  FASTAPI_HEALTH_URL: Joi.string().uri().optional(),
  FASTAPI_INTERNAL_URL: Joi.string().uri().optional(),
  FASTAPI_URL: Joi.string().uri().allow('').optional(),
  ELSA_HEALTH_URL: Joi.string().uri().optional(),
  CORS_ORIGIN: Joi.string().default('http://localhost:3001'),
  DEV_BYPASS_AUTH: Joi.boolean().default(false),
  THROTTLE_TTL: Joi.number().default(60),
  THROTTLE_LIMIT: Joi.number().default(120),
  LOG_LEVEL: Joi.string().valid('trace', 'debug', 'info', 'warn', 'error').default('info'),
});
