import { ConflictException, GoneException, Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { createHash, randomBytes } from 'crypto';
import { DataSource, Repository } from 'typeorm';
import { User } from '../auth/entities/user.entity';
import { CreateWorkspaceInvitationDto } from './dto/invitation.dto';
import { InvitationStatus, WorkspaceInvitation } from './entities/workspace-invitation.entity';
import { WorkspaceMember, WorkspaceMemberStatus, WorkspaceRole } from './entities/workspace-member.entity';
import { WorkspacePermissionService } from './workspace-permission.service';
@Injectable()
export class WorkspaceInvitationsService {
  constructor(@InjectRepository(WorkspaceInvitation) private readonly invitations: Repository<WorkspaceInvitation>, @InjectRepository(User) private readonly users: Repository<User>, @InjectRepository(WorkspaceMember) private readonly members: Repository<WorkspaceMember>, private readonly permissions: WorkspacePermissionService, private readonly dataSource: DataSource) {}
  async create(workspaceId: string, dto: CreateWorkspaceInvitationDto, userId: string) { const caller = await this.permissions.requireRole(userId, workspaceId, [WorkspaceRole.OWNER, WorkspaceRole.ADMIN]); if (dto.role === WorkspaceRole.OWNER && caller.role !== WorkspaceRole.OWNER) throw new ConflictException('Only owners can invite owners'); const email = dto.email.trim().toLowerCase(); if (await this.invitations.exist({ where: { workspaceId, email, status: InvitationStatus.PENDING } })) throw new ConflictException('A pending invitation already exists'); const token = randomBytes(32).toString('base64url'); const invitation = await this.invitations.save(this.invitations.create({ organizationId: caller.organizationId, workspaceId, email, role: dto.role, tokenHash: this.hash(token), invitedBy: userId, expiresAt: new Date(Date.now() + 7*24*60*60_000), acceptedAt: null, revokedAt: null, status: InvitationStatus.PENDING })); return { ...invitation, tokenHash: undefined, ...(process.env.NODE_ENV === 'production' ? {} : { token }) }; }
  async list(workspaceId: string, userId: string) { await this.permissions.requireRole(userId, workspaceId, [WorkspaceRole.OWNER, WorkspaceRole.ADMIN]); return this.invitations.find({ where: { workspaceId }, order: { createdAt: 'DESC' }, select: { tokenHash: false } }); }
  async revoke(workspaceId: string, id: string, userId: string) { await this.permissions.requireRole(userId, workspaceId, [WorkspaceRole.OWNER, WorkspaceRole.ADMIN]); const invitation = await this.invitations.findOne({ where: { id, workspaceId, status: InvitationStatus.PENDING } }); if (!invitation) throw new NotFoundException('Pending invitation not found'); invitation.status = InvitationStatus.REVOKED; invitation.revokedAt = new Date(); await this.invitations.save(invitation); return { revoked: true }; }
  async accept(token: string, userId: string) { return this.dataSource.transaction(async manager => { const invitation = await manager.findOne(WorkspaceInvitation, { where: { tokenHash: this.hash(token) }, lock: { mode: 'pessimistic_write' } }); if (!invitation) throw new NotFoundException('Invitation not found'); const user = await manager.findOneByOrFail(User, { id: userId }); if (user.email.toLowerCase() !== invitation.email.toLowerCase()) throw new ConflictException('Invitation email does not match current user'); if (invitation.status === InvitationStatus.ACCEPTED) { const existing = await manager.findOne(WorkspaceMember, { where: { workspaceId: invitation.workspaceId, userId } }); if (existing) return existing; } if (invitation.status !== InvitationStatus.PENDING) throw new GoneException('Invitation is no longer valid'); if (invitation.expiresAt <= new Date()) { invitation.status = InvitationStatus.EXPIRED; await manager.save(invitation); throw new GoneException('Invitation expired'); } let member = await manager.findOne(WorkspaceMember, { where: { workspaceId: invitation.workspaceId, userId } }); if (member) { member.role = invitation.role; member.status = WorkspaceMemberStatus.ACTIVE; } else member = manager.create(WorkspaceMember, { organizationId: invitation.organizationId, workspaceId: invitation.workspaceId, userId, role: invitation.role, status: WorkspaceMemberStatus.ACTIVE, invitedBy: invitation.invitedBy, joinedAt: new Date() }); member = await manager.save(member); invitation.status = InvitationStatus.ACCEPTED; invitation.acceptedAt = new Date(); await manager.save(invitation); return member; }); }
  private hash(token: string) { return createHash('sha256').update(token).digest('hex'); }
}
